resolver: lts-18.16
extra-deps:
  - github: hslua/hslua
    commit: 3b5637dc28a60a42c6dea2bc0796a754a826691
    subdirs:
      - hslua
      - hslua-classes
      - hslua-core
      - hslua-marshalling
      - hslua-module-path
      - hslua-module-system
      - hslua-module-text
      - hslua-module-version
      - hslua-objectorientation
      - hslua-packaging
      - lua
      - tasty-hslua
      - tasty-lua
  - pandoc-types-1.22.1
ghc-options:
  "$locals": -fhide-source-paths
